# Generated by Django 4.1.7 on 2023-02-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('title', models.CharField(max_length=16, verbose_name='должность')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('image', models.ImageField(upload_to='index/', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команда',
                'db_table': 'corm_team',
            },
        ),
    ]
