# Generated by Django 4.1.7 on 2023-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='картинка'),
        ),
    ]
