# Generated by Django 4.1.7 on 2023-02-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0004_team_about_image_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='имя')),
                ('permission', models.CharField(max_length=32, verbose_name='должность')),
                ('title', models.CharField(max_length=256, verbose_name='описание')),
                ('image', models.ImageField(upload_to='index/', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
        ),
    ]
