# Generated by Django 4.1.7 on 2023-03-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='картинка-номер'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='услуга')),
                ('descr', models.CharField(max_length=256, verbose_name='описание')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'corm_products',
            },
        ),
    ]
