# Generated by Django 4.1.7 on 2023-03-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0010_right_descr_blockq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Заголовок')),
                ('descr', models.CharField(max_length=1048, verbose_name='описание')),
                ('image', models.ImageField(upload_to='elements/', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'left',
                'verbose_name_plural': 'left',
                'db_table': 'corm_left',
            },
        ),
    ]
