# Generated by Django 4.1.7 on 2023-03-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0012_alter_descr_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descr',
            name='first_name',
        ),
    ]
