# Generated by Django 4.1.7 on 2023-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0014_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='color',
            field=models.IntegerField(null=True, verbose_name='цвет'),
        ),
    ]
