# Generated by Django 4.1.7 on 2023-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0017_day_alter_blog_mount_alter_blog_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='day',
            field=models.IntegerField(verbose_name='день'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
