# Generated by Django 4.1.7 on 2023-03-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0018_alter_blog_day_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
