# Generated by Django 4.1.7 on 2023-03-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0019_contact_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_blog',
            options={'verbose_name': 'blog_email_contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AddField(
            model_name='blog',
            name='item_category',
            field=models.CharField(max_length=32, null=True, verbose_name='постов на разные темы'),
        ),
        migrations.AlterModelTable(
            name='contact_blog',
            table='main_blog',
        ),
        migrations.CreateModel(
            name='Blogcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12, verbose_name='название-категории')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('count', models.IntegerField(verbose_name='колл')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
                ('category_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.blog', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'blog-cat',
                'verbose_name_plural': 'blog-cat',
                'db_table': 'corm_blog_category',
            },
        ),
    ]
