# Generated by Django 4.1.7 on 2023-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0020_alter_contact_blog_options_blog_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_blog',
        ),
    ]
