# Generated by Django 4.1.7 on 2023-03-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0022_remove_blogcategory_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'instagram',
                'verbose_name_plural': 'instagram',
                'db_table': 'corm_instagram',
            },
        ),
    ]
