# Generated by Django 4.1.7 on 2023-03-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corm', '0023_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'posts',
                'verbose_name_plural': 'posts',
                'db_table': 'corm_posts',
            },
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='текст')),
                ('date', models.DateField(verbose_name='дата')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corm.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'recent',
                'verbose_name_plural': 'recent',
                'db_table': 'corm_recent',
            },
        ),
    ]
